### ISSUE TITLE
Merge into ghcid (if you wanted)

### ISSUE THREAD

**Issue by ndmitchell** [cloudhead/neovim-ghcid#5]
Great work. I've added a link to this project from the ghcid project, see https://github.com/ndmitchell/ghcid#ghcid-integration.

Have you considered merging this plugin into the ghcid repo? If it's only one file of plugin, and you think it won't grow beyond that, I'd be happy to accept a pull request merging it into the ghcid repo, and distributing it with ghcid as a data file. I don't use neovim (or even any flavour of vim), so I would expect other users (e.g. you) to keep it up to date and improve it.

Of course, it is entirely up to you what you want to do with this project - I'm equally happy to stick with just linking onward to this project for neovim support.

**Comment by cloudhead** [comment]
Hey, thanks, ghcid has been very good to me, I'd definitely consider merging and maintain it from there. The project is mostly feature-complete, so it's not going to grow much. I would like to include vim documentation too though, so it's technically two files :) and would need push access to manage the project efficiently. Overall I think it's a good idea, it would make the haskell tooling story just a bit better!

**Comment by ndmitchell** [comment]
I've granted you push access. In general, if they are changes to the core of ghcid, probably better to send them in as a pull request. However, for vim stuff, whatever you think is best. Not sure where the stuff should end up - perhaps a neovim directory? Perhaps not? Should the plugin be distributed as a data file with ghcid? Do whatever you think works best.

**Comment by cloudhead** [comment]
Awesome. Of course I wouldn't push directly on ghcid code, but would be useful for the plugin. I have an idea of where things could end up with regards to the plugins, will open a PR once ready.

Cheers!
