### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by pkamenarsky** [cloudhead/neovim-ghcid#6]
After typing :Ghcid, this is what happens:

[Errors](http://i.imgur.com/INV8HJX.png)

It keeps working after that, so I don't know how critical these are.

**Comment by cloudhead** [comment]
Thanks for the bug report, could you check if you're still having the issue with the latest master? I'm not sure how to reproduce this.

**Comment by pkamenarsky** [comment]
Seems to work now! Thanks :)
