### ISSUE TITLE
g:ghcid_keep_open = 0 requires set hidden

### ISSUE THREAD

**Issue by nanotech** [cloudhead/neovim-ghcid#7]
With the default configuration of `g:ghcid_keep_open = 0`, if `hidden` isn't set, successful runs of ghcid close the window and the process gets killed, displaying

    Error detected while processing function 7:
    line    2:
    Ghcid: Exited with status 1

I found how to fix this in the [reddit announcement thread][1], but a mention of `hidden` in the readme would be good too.

If you'd like `nohidden` to work out of the box (still the default in neovim), using a default of `g:ghcid_keep_open = !&hidden` would work.

Thanks for the nice plugin.

[1]: https://www.reddit.com/r/haskell/comments/4zixt2/ann_neovimghcid/d6war10

**Comment by cloudhead** [comment]
Good idea, will look into this.

**Comment by cloudhead** [comment]
Fixed in https://github.com/cloudhead/neovim-ghcid/commit/e3ad8a6b9abdcb69bbfe45563ac7432f81a9841f
Doc: https://github.com/cloudhead/neovim-ghcid/commit/ab30393d6bc93dd5c6696f57a05d468aa5a5c5de

**Comment by nanotech** [comment]
Thanks!
